### ISSUE TITLE
Submit package to Package Control

### ISSUE THREAD

**Issue by roaldnefs** [warpnet/SublimeLinter-salt-lint#11]
Add required configuration to add `SublimeLinter-salt-lint` to Package Control.

For more information about submitting a package see: https://packagecontrol.io/docs/submitting_a_package.

**Comment by atezet** [comment]
This linter is submitted through SublimeLinter's package control: https://github.com/SublimeLinter/package_control_channel. See: https://packagecontrol.io/packages/SublimeLinter-contrib-salt-lint
